# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25715dd363a13352261ebacc751bec4d60fd438e07546a8363a74fb3aa57e9945af638d716f3cc54be9a57fd23aa2a34cf68d9737196bd7df6e83a9497a735b

test:
  secret_key_base: 0aff5af4fb926af99b664709bfebbb7fc41c0e871c31ff00c801b3dabb5349feef8667546d13acc632ec96b900b10300ae89adba71d1598d17d760b11093b0e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
